### ISSUE TITLE
Dask-CHTC user guide

### ISSUE THREAD

**Issue by JoshKarpel** [CHTC/chtc-website-source#118]
https://github.com/CHTC/dask-chtc (repo) / https://dask-chtc.readthedocs.io/en/latest/?badge=latest (docs)

Dask-CHTC is at a point where it is usable (and hopefully useful) to people. I think we can *probably* safely support ~10 users on submit3 right now, and will definitely be able to do so once https://crt.cs.wisc.edu/rt/Ticket/Display.html?id=101264 happens.

Given that, how do we feel about adding a CHTC user guide pointing toward Dask-CHTC? I'm imagining the content mostly being about what kind of workflows would drive you toward using Dask (existing Dask-using program; wants master-worker in Python; wants "MPI-like" larger-than-single-machine-memory calculations; https://docs.dask.org/en/latest/why.html might be helpful), then pointing at the Dask-CHTC external docs linked above.

I think a necessary prerequisite of this guide going up is the RCFs reviewing the Getting Started workflow at least, and maybe playing with Dask a little as well so they can give better advice to people.

Is the infrastructure ticket above also a blocker? Any other blockers to making Dask-CHTC "generally available"?

**Comment by ChristinaLK** [comment]
I like the idea of having at least a page (even if not publicly linked) so we have the information written down and links in a findable place.
