### ISSUE TITLE
updates to hpc guide

### ISSUE THREAD

**Issue by ChristinaLK** [CHTC/chtc-website-source#120]
* partition table
* mention EL7 + version of SLURM (?)

**Comment by jmvera255** [comment]
what needs to be changed regarding the partition table?

**Comment by ChristinaLK** [comment]
we should confirm the number of servers that will be available when accounts are available.

**Comment by ChristinaLK** [comment]
Based on 9/29 call - remove univ partition line.

**Comment by ChristinaLK** [comment]
Completed by Jess.
