### ISSUE TITLE
Add reference to the PATh website

### ISSUE THREAD

**Issue by bbockelm** [CHTC/chtc-website-source#145]
Now that it's started, we should refer to PATh (https://path-cc.io/) from the CHTC website.

**Comment by ChristinaLK** [comment]
@bbockelm I'm thinking either a button under "Other Resources" or "About". @lmichael107 what do you think?

**Comment by ChristinaLK** [comment]
@lmichael107 to report back after Path meeting!

**Comment by CannonLock** [comment]
Completed in 2021
