### ISSUE TITLE
Learned CHTC basics, here's what I've noticed

### ISSUE THREAD

**Issue by jsta** [CHTC/chtc-website-source#177]
I noticed a few inconsistencies in the docs:

 * [At one point](https://chtc.cs.wisc.edu/file-availability.shtml), the docs say not to list squid files in `transfer_input_files` but this is done in many of the examples in the other pages.
 * On the docker page, it says that interactive sessions are _coming soon_ but it seems they are already here?
 * It seems that tarballs created from interactive jobs (as shown in the R and conda docs) can't be used in subsequent jobs unless their permissions are modified. I didn't see this shown anywhere in the docs.

**Comment by ChristinaLK** [comment]
Thanks @jsta! 

The tarball issue from interactive jobs is new. What error(s) did you get?

**Comment by jsta** [comment]
I follow the [conda instructions](https://chtc.cs.wisc.edu/conda-installation.shtml) uploading the results of `conda pack` to squid. My job is held.  

If I change the permissions on the squid tarball, everything proceeds without being held. My code is at: 
https://github.com/jsta/wisc_chtc_examples/blob/main/example_conda/Makefile

**Comment by ChristinaLK** [comment]
so to recap: when you put the file in /squid, it doesn't have the right permissions be default (isn't world-readable)?

That has come up before; I'll take that back to our team to see what's going on there.

**Comment by jsta** [comment]
Yes, I believe so

**Comment by jmvera255** [comment]
I just did a test and it looks like conda-pack is setting the permissions of the environment tarball to `600` while running something like `touch file.tar.gz` sets the permissions to `644`. The `600` permissions are too restrictive for hosting the files in Squid and prevents HTCondor from being able to access the file which results in the job going on hold.

@jsta this seems to be a new behavior from conda/conda-pack. We will add a step to our conda guide that revises that permissions of the `env.tar.gz` file just in case the tarball ends up being >100MB in size.

**Comment by jmvera255** [comment]
@jsta thank you again for your feedback and contribution! We have addressed all the items in this issue
