### ISSUE TITLE
broken link on HPC basic use guide

### ISSUE THREAD

**Issue by jmvera255** [CHTC/chtc-website-source#33]
the "SLURM's user guide" link in section 3.c is broken. Originally pointed to /linux/slurm/quickstart.html, but wasn't sure what a suitable replacement link should be. I found https://slurm.schedmd.com/quickstart.html and it looked like it might be similar to what that previous link was pointing to. I can make the edit if we like the content at this new url

**Comment by ChristinaLK** [comment]
I don't know what was there before, but this seems like a good replacement. 

Another option might be to remove this section altogether. @lmichael107, thoughts?

**Comment by lmichael107** [comment]
sounds good to me
