### ISSUE TITLE
Colab guide

### ISSUE THREAD

**Issue by ChristinaLK** [CHTC/chtc-website-source#343]
There's a skeleton guide in `uw-research-computing/colab-to-chtc.md`

Needs to be fleshed out with material from https://colab.research.google.com/drive/14qDwE6orV5DalBO4aO6zyqqLYuiHXNOv?usp=sharing

**Comment by PatStiles** [comment]
Description Section:
2.) remove "magic" command for more concise language
3.) remove first person phrasing "(which leads to a slimmer docker, and I haven't encountered any issues with versioning doing this like I have with pip freeze)"

Code:
Step 6: add %%bash before command section within comments
Step 8: remove angle brackets
Step 10: remove angle brackets
