### ISSUE TITLE
Error at the end of high-memory-jobs.shtml

### ISSUE THREAD

**Issue by sameerd** [CHTC/chtc-website-source#46]
At the end of http://chtc.cs.wisc.edu/high-memory-jobs.shtml it says
`
[an error occurred while processing this directive]
`

Maybe related to this line? 
https://github.com/CHTC/chtc-website-source/blob/10fe3a67ef3ba4d0f8aff02189950b1d14fb42d1/high-memory-jobs.shtml#L266

**Comment by ChristinaLK** [comment]
Ah, good catch. It is that line that needs to be deleted.
