### ISSUE TITLE
HTML closing tags missing

### ISSUE THREAD

**Issue by sameerd** [CHTC/chtc-website-source#52]
https://github.com/CHTC/chtc-website-source/blob/469d4f2873fa58f26ee9ac3e30030b923eb8159d/file-availability.shtml#L17-L21

Lines 19 and 20 are missing a closing `</li>` tag. This is causing the webpage to render a little weirdly on my browser.

**Comment by ChristinaLK** [comment]
@youminhan can you convert this page to markdown tomorrow or next week?

**Comment by jmvera255** [comment]
this has been resolved by conversion to markdown
