### ISSUE TITLE
"Computing Guides" top banner incorrect background color

### ISSUE THREAD

**Issue by aowen-uwmad** [CHTC/chtc-website-source#544]
Specifically looking at `/uw-research-computing/guides.html` in comparison to all the other pages.  The topmost banner on the page, with the "University of Wisconsin - Madison", "Go to CHTC Home", and "Request Account" links, is a much lighter red than the corresponding banner on the other pages, for example `/uw-research-computing/index.html`.  I suspect it's due to the fact that the 'guides' page is an `.html` document, while the other webpages are `.md`.

**Comment by CannonLock** [comment]
Fixed when I updated the stylesheet.
