### ISSUE TITLE
Adjust font size of inline code in headings

### ISSUE THREAD

**Issue by aowen-uwmad** [CHTC/chtc-website-source#570]
In headings, the font size of inline code that is formatted in Markdown with backticks (\`) is considerably smaller than surrounding heading text.  Several examples of this can be found in the "Submitting Multiple Jobs Using HTCondor" page:
* https://chtc.cs.wisc.edu/uw-research-computing/multiple-jobs#:~:text=Submit%20Multiple%20Jobs%20Using%20queue 
* https://chtc.cs.wisc.edu/uw-research-computing/multiple-jobs#:~:text=1.%20Use%20queue%20N%20in%20you%20HTCondor%20submit%20files

Presumably there is a way to address this.  If not, then I think we should replace instances like these with quotes, i.e. "queue" instead of \`queue\`.

**Comment by CannonLock** [comment]
This will take html to fix, if you are willing to accept that burden when writing docs in the future you can use 

`<h*>Non Code Header with <code class="h*">some code block in it</code></h*>`

Otherwise '' is a solid option.

**Comment by aowen-uwmad** [comment]
So instead of 
```
# Submit Multiple Jobs Using `queue`
```
it would be 
```
<h*>Submit Multiple Jobs Using <code class="h*">queue</code></h*>
```
inside of the Markdown file?
(I'm not very good at html...)

**Comment by aowen-uwmad** [comment]
And for a subheading, would the html tag change?  Thinking about how to rewrite
```
## 1. Use `queue N` in you HTCondor submit files
```

**Comment by CannonLock** [comment]
Yeah sorry, the * is the number of hashes. When converting md to html the hashes represent the header tag size.

`
# h1 header
## h2 header
### h3 header
`

So for your example it would be 

`<h2>1. Use <code class="h2">queue</code> N in you HTCondor submit files</h2>`

Where the two #'s are converted to a h**2** tag for html.

**Comment by aowen-uwmad** [comment]
Thanks!

**Comment by aowen-uwmad** [comment]
I've made the changes in `preview-fix-code-in-headings` branch.  Waiting for preview before creating PR to make sure it worked correctly.  Will link this issue.
