### ISSUE TITLE
GPU Lab page icons are too large

### ISSUE THREAD

**Issue by agitter** [CHTC/chtc-website-source#576]
Originally the three icons at https://chtc.cs.wisc.edu/uw-research-computing/gpu-lab.html were smaller and spanned a single row on my desktop browser. Now they are large and only fit one icon per row such that they wrap and form a column of icons

@CannonLock do you have an easy way to rescale them? We're preparing a Morgridge news story about the GPU lab that could go out as soon as tomorrow March 29. It will link to this CHTC page, so I wanted to make sure the page looks okay.

**Comment by CannonLock** [comment]
@agitter Fix is live, thanks for the issue
