### ISSUE TITLE
DAGMan youtube video link display broken

### ISSUE THREAD

**Issue by aowen-uwmad** [CHTC/chtc-website-source#583]
On the DAGMan guide page (https://chtc.cs.wisc.edu/uw-research-computing/dagman-workflows), the link to the Youtube video used to be embedded in some fashion.  I don't remember if it was simply a video preview image, or if it was an embedded video player.

Relevant file should be `_uw-research-computing/dagman-workflows.md`.

I'm seeing the following, checked on multiple browsers and devices:
![image](https://user-images.githubusercontent.com/60940495/234121406-7693c49f-caa8-482f-b929-d65ba1b07661.png)

**Comment by CannonLock** [comment]
I am surprised it ever worked, the src should be https://raw.githubusercontent.com/OSGConnect/connectbook/master/images/dagman-talk-screenshot.png. 

I will fix tomorrow.
