### ISSUE TITLE
Comments on conda guide

### ISSUE THREAD

**Issue by agitter** [CHTC/chtc-website-source#62]
Here are a few initial thoughts about http://chtc.cs.wisc.edu/conda-installation

Installing Miniconda every time in each job (Option 2) uses the latest versions of the conda packages.  We've run into big problems when package versions change and now are in the habit of pinning versions of "important" packages.  A simple modification to help with this would be to have the example pin the versions of numpy and matplotlib.  Our group uses environment files as a more complete solution so that we can recreate and distribute the environments (more or less).  There is an art to using environment files though, and it gets complicated quickly to figure out which packages can be pinned and which need to be flexible to allow installation on different machines.

For complex environments, users will eventually face unsatisfiable dependencies or requirements.  Should the guide alert users to this possibility, tell them how to recognize this error, and/or give guidance on where to go for help?

**Comment by JoshKarpel** [comment]
I'm hesitant to explicitly pin versions in the example, because I'm worried that people will blindly copy them when they become out of date in the future. However, I very much like the idea of introducing version pinning in general and environment files in particular. I could see that discussion replacing Option 2 (which I suspect we should never tell anyone to do for the same reason they shouldn't `pip install` in a job; @ChristinaLK , do we know of any use cases that require it?) as the second half of the guide.

I'm tempted to say the unsatisfiable dependencies are out of scope for a CHTC guide, and the error messages are usually pretty explicit. Do you often run into them in conda @agitter ? What kind of packages end up being involved in these conflicts?

**Comment by agitter** [comment]
> I'm tempted to say the unsatisfiable dependencies are out of scope for a CHTC guide

I agree with this

> the error messages are usually pretty explicit

I don't have examples on hand, but I generally disagree.  Someone who is accustomed to Googling quoted phrases from error messages can usually figure out what's going on.  I don't find conda error messages (related to dependencies and otherwise) interpretable without that.

Given the two above statements, a concrete suggestion may be to add a phrase "If you encounter errors with conda, do X" where X might be go to the conda project's GitHub issues or something else outside of CHTC.

I run into unsatisfiable dependencies in conda a couple times a year.  The typical workflow is that I encounter an conda environment created via `conda env export` (without `--from-history`) and want to get it running on a new machine or new platform.  Some of the packages involved have been the major players in the scientific Python stack, but I don't recall specific scenarios.

**Comment by ChristinaLK** [comment]
I think it's appropriate to add a note about version locking/specifications or env files and then point people to (say) the conda docs. 

I don't know if we can address unsatisfiable dependencies specifically, but could add a note to the effect of "if your environment isn't building/working, please email us". I like @agitter's suggestion above.

**Comment by ChristinaLK** [comment]
@agitter your group has used the second option (install per job) - correct? is that because there wasn't yet a solution like conda-pack or were there other reasons to install per job?

**Comment by agitter** [comment]
It was a mixture of reasons.  The primary reason is that conda-pack wasn't available when we started using conda (or we weren't aware of it).

The secondary reason we still like it is for continuous integration-related reasons.  We want to provide source code and conda environment yml files for our mature projects and be confident a new user can run that code in the environment.  Because conda installs are always a moving target, running our real workloads in newly created environments helps us detect problems.  It also helps us confidently report in publications which versions of software were used to generate results.  That can also be achieved with logging, but we had problems with a logging-based strategy in the past.  Different individuals working on the same project were using subtly different versions of packages that produced inconsistent results.

That said, I will definitely consider using conda-pack for CHTC work and separate lightweight continuous integration testing moving forward.  I haven't studied conda-pack enough to know how it compares to a environment yml file for maintainability, portability across platforms, and archiving.
