### ISSUE TITLE
/staging guide changes

### ISSUE THREAD

**Issue by ChristinaLK** [CHTC/chtc-website-source#77]
As discussed in Ops on 2020-07-01

- recommend tarring output straight to /staging instead of copying
- add note to GPU/machine learning guide calling out that their data access patterns might not fall into same recommendations as /staging guide and to contact us. 
- maybe change /staging guide to be like: best case, copy files and have things zipped, otherwise talk to us.

**Comment by jmvera255** [comment]
working on it

**Comment by jmvera255** [comment]
@ChristinaLK thoughts on how to proceed with incorporating these changes into PR #187??

**Comment by ChristinaLK** [comment]
I think you can ignore the first bullet point. 
For the second...maybe a note under the "Who Should Use /staging" header?
