### ISSUE TITLE
Funky formatting on "Connecting" page..

### ISSUE THREAD

**Issue by JacobRPrice** [CHTC/chtc-website-source#8]
There are a couple formatting mistakes on the connecting page (http://chtc.cs.wisc.edu/connecting.shtml). 

**"If you haven't, see our getting started page."**
![Screen Shot 2020-01-08 at 11 57 07 AM](https://user-images.githubusercontent.com/11934394/72002998-1ca92700-320e-11ea-800b-bb2c7ff26a66.png)

**Formatting around "Username and Password"**
![Screen Shot 2020-01-08 at 11 58 49 AM](https://user-images.githubusercontent.com/11934394/72003090-4a8e6b80-320e-11ea-9a7b-076e6b8d58ec.png)

**2. Logging In**
![Screen Shot 2020-01-08 at 11 59 38 AM](https://user-images.githubusercontent.com/11934394/72003157-65f97680-320e-11ea-85e3-10f8956b2d07.png)

Hope that helps!

Jake

**Comment by ChristinaLK** [comment]
Yes, thank you!
