### ISSUE TITLE
Improve ResearchDrive page

### ISSUE THREAD

**Issue by bbockelm** [CHTC/chtc-website-source#81]
After a few rounds with the ResearchDrive page:

1.  We should have an example of how to download all the files in a directory.  I don't think it's safe to assume the user has the quota space available to make a separate tarball of the dataset to process.
2.  It's worthwhile to note that other servers on campus may be able to follow the same directions.  For example, `smph` appears to have a similar setup that can be used as the source.

**Comment by ChristinaLK** [comment]
for 2., we have a very brief note at the beginning that this guide may apply in other contexts but could expand/move it in the guide.

**Comment by jmvera255** [comment]
@bbockelm I can submit a PR with this additional example for request 1

**Comment by jmvera255** [comment]
the requests in this issue have been addressed
