### ISSUE TITLE
Document CHTC Docker registry

### ISSUE THREAD

**Issue by JoshKarpel** [CHTC/chtc-website-source#89]
CHTC has its own Docker registry that users can push images to, but it isn't documented on the user-facing website. Assuming there isn't some reason to not document it, we should, in an effort to make it easier for our users to use Docker. @lmichael107 ?

I have some thoughts about building their images for them as well, now that we can build images on the build machines, but that's another project...

Quick notes: to get an image into our registry, you tag it with the prefix `dockerreg.chtc.wisc.edu` and then push it as normal:

```console
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              20.04               1e4467b07108        2 weeks ago         73.9MB
centos              7                   5e35e350aded        9 months ago        203MB
jekyll/jekyll       latest              2754bfa01869        10 months ago       547MB
hello-world         latest              fce289e99eb9        19 months ago       1.84kB
mysql               8.0.13              102816b1ee7d        19 months ago       486MB
$ docker tag --help
Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]
Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
$ docker tag ubuntu:20.04 dockerreg.chtc.wisc.edu/ubuntu:20.04
$ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
ubuntu                           20.04               1e4467b07108        2 weeks ago         73.9MB
dockerreg.chtc.wisc.edu/ubuntu   20.04               1e4467b07108        2 weeks ago         73.9MB
centos                           7                   5e35e350aded        9 months ago        203MB
jekyll/jekyll                    latest              2754bfa01869        10 months ago       547MB
hello-world                      latest              fce289e99eb9        19 months ago       1.84kB
mysql                            8.0.13              102816b1ee7d        19 months ago       486MB
$ docker push dockerreg.chtc.wisc.edu/ubuntu:20.04
The push refers to repository [dockerreg.chtc.wisc.edu/ubuntu]
095624243293: Pushed
a37e74863e72: Pushed
8eeb4a14bcb4: Pushed
ce3011290956: Pushed
20.04: digest: sha256:60f560e52264ed1cb7829a0d59b1ee7740d7580e0eb293aca2d722136edb1e24 size: 1152
```

Then to use it you do something like

```
docker_image = dockerreg.chtc.wisc.edu/ubuntu:20.04
```

in your submit description.

Important note: images are not private; anyone on our network can pull them (mostly just like a public image on Docker Hub).

**Comment by ChristinaLK** [comment]
I would prefer NOT to have this documented right now: 
1) lack of "enforceability" (I'll put more details in slack). 
2) we spend zero time maintaining this registry and don’t really have dedicated staff time to do so

If we have a conversation (say in Ops) that this is something we DO want to support and either Moate/Tim/a student takes it on *and* we have a conversation about recommendations (should people *always* use this? When?), then I would feel okay putting it on the website.
